### ISSUE TITLE
Método Markowitz

### ISSUE THREAD

**Issue by Danahirmt** [czammar/MNO_finalproject#1]
Selección de la metodología a implementar para el desarrollo del proyecto.
- Escribirla en el README

Deberá contener:

[ ] Descripción del tema
[ ] Metodología a realizar

**Comment by izmfc** [comment]
veo que las fórmulas no se ven bien en el readme, estuve investigando y parece que no es tan sencillo mostrar fórmulas en general en el readme, igual podríamos hacer un documento por aparte donde se visualicen correctamente  y solamente en el readme hacer referencia al documento.

**Comment by Yalidt** [comment]
En el readme encontraran el objetivo del problema y la solución algebraica de la optimización.
