### ISSUE TITLE
1.a Extracción de los datos desde Yahoo Finance

### ISSUE THREAD

**Issue by Yalidt** [czammar/MNO_finalproject#16]
Crear una función que extraiga los precios de las acciones de 50 empresas, para los últimos 5 años:
Industria *Energy*- SASE:2222, NYSE:XOM, NYSE:CVX,ENXTAM:RDSA, NSEI:RELIANCE
Industria *Real Estate* -NYSE:AMT, NYSE:CCI, NYSE:PLD, NasdaqGS:QEIX, NYSE:DLR
Industria *Materiales*- NYSE:LIN, ASX:BHP, LSE:RIO, ENXTPA:AI, SASE:2010
Industrials Company- NSYE:LMT, NYSE:UNIP, NYSE:HON, NYSE:RTX, NYSE:UPS
Industria *Discretionary consumer* -NasdaqGS:AMZN,NYSE:BABA, NYSE:HD,ENXTPA:MC, TSE:7203
Industria *Staples*- NYSE:WMT, SWX:NESN, NYSE:PG, NYSE:KO, NasdaqGS:PEP
Industria *Health Care*- NYSE:JNJ, SWX:ROG, NYSE:UNH,NYSE:PFE, SYSE:MRK
Industria *Financials*- ARCA:VTI, ARCA:VOO, NYSE:BRK.A, NYSE:JPM, SEHK:1398
Industria *Information Technology* :NasdaqGS:MSTF, NasdaqGS:APPL, NYSE:V, KOSE:A005930, NYSE:MA
Industria *Communication* - NasdaqGS:GOOG.L, NasdaqGS:FB, SEHK:700,NYSE:VZ, NYSE:T

**Comment by izmfc** [comment]
se cambió NasdaqGS:QEIX por 0688.HK pues Equinix, Inc. parece no ser Real Estate, y se cambió  SASE:2222 por COP pues  SASE:2222 tenía muy pocos días informados
