### ISSUE TITLE
1.b Limpieza y 1c.Transformación

### ISSUE THREAD

**Issue by Yalidt** [czammar/MNO_finalproject#17]
Una vez extraídos los datos se necesita revisar si hay datos faltantes, que estén en la misma frecuencia de tiempo ( mismo numero de columnas para todas las acciones), en caso de que haya datos faltantes podemos imputar con la moda del precio para esa acción.

**Comment by izmfc** [comment]
se eliminaron los fines de semana y los NA's se llenaron con el precio del día previo
