### ISSUE TITLE
Resultados revisión Etapa 1

### ISSUE THREAD

**Issue by Yalidt** [czammar/MNO_finalproject#37]
Hola, Itzel

Ya esta la revisión de tu código en la carpeta de Revisión/revision_extraer_datos_test.ipynb
Los comentarios del equipo de revisión en general son los siguientes:
1)Las funciones no están documentadas y sugieren que se ponga un ejemplo de lo que realiza tu algoritmo en la documentación.
2)Los parámetros de entrada en el rango de fechas(inicio y final) de extracción comentan que debería ser un parámetro general para que se puede extraer cualquier rango de fechas.

Puedes encontrar la información detallada en el notebook.

**Comment by izmfc** [comment]
ya está el pull request con los cambios
