### ISSUE TITLE
Funciones auxiliares para solver con método de Newton

### ISSUE THREAD

**Issue by Danahirmt** [czammar/MNO_finalproject#63]
1. Creación de funciones auxiliares:
  - line_search_by_backtracking
  - line_search_for_residual_by_backtracking
  - compute_error
  - norm_residual
Basarse en los siguientes scripts:
- https://github.com/ITAM-DS/analisis-numerico-computo-cientifico/blob/e6773d6e62f12e34a084a30d47760b66ed5bbc64/temas/IV.optimizacion_convexa_y_machine_learning/algoritmos/Python/line_search.py#L3

- https://github.com/ITAM-DS/analisis-numerico-computo-cientifico/blob/e6773d6e62f12e34a084a30d47760b66ed5bbc64/temas/IV.optimizacion_convexa_y_machine_learning/algoritmos/Python/utils.py#L28

**Comment by czammar** [comment]
@Danahirmt puedes asignar la segunda parte a otro issue; creo que está en otro contexto lo de proponer el punto factible, así ya mando mis scripts al merge
